from django import template
register = template.Library()
TEXTS = {
    "home":{"ky":"Башкы бет","ru":"Главная","en":"Home"},"regions":{"ky":"Аймактар","ru":"Регионы","en":"Regions"},"tours":{"ky":"Турлар","ru":"Туры","en":"Tours"},"categories":{"ky":"Категориялар","ru":"Категории","en":"Categories"},"about":{"ky":"Биз жөнүндө","ru":"О нас","en":"About us"},"contact":{"ky":"Байланыш","ru":"Контакты","en":"Contact"},
    "footer_tagline":{"ky":"Кыргызстандын кооздугун биз менен бирге табыңыз!","ru":"Откройте красоту Кыргызстана вместе с нами!","en":"Discover the beauty of Kyrgyzstan with us!"},"explore":{"ky":"Навигация","ru":"Навигация","en":"Explore"},"popular_regions":{"ky":"Популярдуу аймактар","ru":"Популярные регионы","en":"Popular regions"},"rights":{"ky":"Бардык укуктар корголгон.","ru":"Все права защищены.","en":"All rights reserved."},
    "discover_kg":{"ky":"Кыргызстан —","ru":"Кыргызстан —","en":"Kyrgyzstan —"},"hero_title_2":{"ky":"жаратылыштын керемети!","ru":"удивительная красота природы!","en":"where nature amazes!"},"hero_desc":{"ky":"Уникалдуу турлар, унутулгус тажрыйбалар жана чыныгы кыргыз меймандостугу!","ru":"Уникальные туры, незабываемые впечатления и настоящее кыргызское гостеприимство!","en":"Unique tours, unforgettable experiences and genuine Kyrgyz hospitality!"},"find_adventure":{"ky":"Турларды көрүү","ru":"Смотреть туры","en":"Explore tours"},"see_more":{"ky":"Видео көрүү","ru":"Смотреть видео","en":"Watch video"},
    "categories_label":{"ky":"КАТЕГОРИЯЛАР","ru":"КАТЕГОРИИ","en":"CATEGORIES"},"choose_category":{"ky":"Өзүңүзгө ылайыктуу саякатты тандаңыз","ru":"Выберите свой формат путешествия","en":"Choose your way to travel"},"seven_regions":{"ky":"ЖЕТИ ОБЛАСТЬ","ru":"СЕМЬ ОБЛАСТЕЙ","en":"SEVEN REGIONS"},"discover_regions":{"ky":"Кыргызстанды аймактар аркылуу ачыңыз","ru":"Откройте Кыргызстан по регионам","en":"Discover Kyrgyzstan by region"},"regions_desc":{"ky":"Ар бир областьтын өзүнүн жаратылышы, тарыхы жана өзгөчө кооз жерлери бар.","ru":"У каждого региона свой характер, природа, история и уникальные места.","en":"Every region has its own character, nature, history and unique places."},"all_regions":{"ky":"Бардык областтар","ru":"Все области","en":"All regions"},"featured_routes":{"ky":"ТАНДАЛГАН МАРШРУТТАР","ru":"ИЗБРАННЫЕ МАРШРУТЫ","en":"FEATURED ROUTES"},"go_beautiful":{"ky":"Кооз жерлерге жолго чыгалы.","ru":"Поехали туда, где красиво.","en":"Let's go where beauty begins."},"all_tours":{"ky":"Бардык турлар","ru":"Все туры","en":"All tours"},"days_short":{"ky":"күн","ru":"дн.","en":"days"},"tours_count":{"ky":"тур","ru":"тура","en":"tours"},"places":{"ky":"кооз жер","ru":"мест","en":"places"},
    "region":{"ky":"Область","ru":"Область","en":"Region"},"gallery":{"ky":"ГАЛЕРЕЯ","ru":"ГАЛЕРЕЯ","en":"GALLERY"},"region_photos":{"ky":"Бул жерди сүрөттөрдөн көрүңүз","ru":"Посмотрите регион в фотографиях","en":"See this region in photos"},"beautiful_places":{"ky":"КООЗ ЖЕРЛЕР","ru":"КРАСИВЫЕ МЕСТА","en":"BEAUTIFUL PLACES"},"places_in_region":{"ky":"Бул областта кайда барууга болот?","ru":"Что стоит увидеть в этой области?","en":"What should you see here?"},"add_region_photos":{"ky":"Админ панелден бир нече сүрөт кошуңуз.","ru":"Добавьте несколько фотографий через админ-панель.","en":"Add multiple photos from the admin panel."},"no_places":{"ky":"Азырынча кооз жерлер кошула элек.","ru":"Красивые места пока не добавлены.","en":"No beautiful places have been added yet."},
    "day_by_day":{"ky":"Күн сайын.","ru":"День за днём.","en":"Day by day."},"program_soon":{"ky":"Программа жакында кошулат.","ru":"Программа скоро будет добавлена.","en":"The itinerary will be added soon."},"regional_routes":{"ky":"АЙМАКТАГЫ ТУРЛАР","ru":"ТУРЫ РЕГИОНА","en":"REGIONAL TOURS"},"no_tours":{"ky":"Азырынча турлар жок.","ru":"Пока нет туров.","en":"No tours yet."},"choose_route":{"ky":"Өз маршрутуңузду тандаңыз.","ru":"Выберите свой маршрут.","en":"Choose your route."},"tours_desc":{"ky":"Күнүнө, категориясына жана аймагына жараша тандалган саякаттар.","ru":"Путешествия по длительности, категории и региону.","en":"Journeys sorted by duration, category and region."},"route":{"ky":"Маршрут","ru":"Маршрут","en":"View route"},
    "booking":{"ky":"Брондоо","ru":"Бронирование","en":"Booking"},"per_person":{"ky":"адам","ru":"чел.","en":"person"},"send_request":{"ky":"Өтүнмө жөнөтүү","ru":"Оставить заявку","en":"Send request"},"call":{"ky":"Чалуу","ru":"Позвонить","en":"Call"},"write_whatsapp":{"ky":"WhatsApp аркылуу жазуу","ru":"Написать в WhatsApp","en":"Message on WhatsApp"},"choose_language":{"ky":"Тилди тандаңыз","ru":"Выберите язык","en":"Choose language"},"kyrgyz":{"ky":"Кыргызча","ru":"Кыргызский","en":"Kyrgyz"},"russian":{"ky":"Орусча","ru":"Русский","en":"Russian"},"english":{"ky":"Англисче","ru":"Английский","en":"English"},"about_title":{"ky":"Кыргызстанды жакындан тааныңыз","ru":"Познакомьтесь с Кыргызстаном ближе","en":"Experience Kyrgyzstan up close"},"about_text":{"ky":"Тоолор, көлдөр, капчыгайлар жана көчмөндөрдүн салты — баары бир сапарда.","ru":"Горы, озёра, ущелья и кочевая культура — всё в одном путешествии.","en":"Mountains, lakes, valleys and nomadic culture — all in one journey."}
}
@register.simple_tag(takes_context=True)
def site_text(context,key):
    lang=context.get("LANGUAGE_CODE","ru")[:2]; return TEXTS.get(key,{}).get(lang,TEXTS.get(key,{}).get("ru",key))
@register.filter
def localized(obj,field):
    lang=getattr(obj,"_lang","ru")[:2]; value=getattr(obj,f"{field}_{lang}",None); return value or getattr(obj,f"{field}_ru","")
