from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Category', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('slug',models.SlugField(unique=True)),('name_ky',models.CharField(max_length=120)),('name_ru',models.CharField(max_length=120)),('name_en',models.CharField(max_length=120)),('description_ky',models.TextField(blank=True)),('description_ru',models.TextField(blank=True)),('description_en',models.TextField(blank=True)),('icon',models.CharField(default='🏔️',max_length=20)),('sort_order',models.PositiveIntegerField(default=0)),('is_active',models.BooleanField(default=True))],options={'ordering':['sort_order','name_ru'],'verbose_name':'Категория','verbose_name_plural':'Категории'}),
        migrations.CreateModel(name='Region', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('slug',models.SlugField(unique=True)),('name_ky',models.CharField(max_length=120)),('name_ru',models.CharField(max_length=120)),('name_en',models.CharField(max_length=120)),('short_description_ky',models.TextField(blank=True)),('short_description_ru',models.TextField(blank=True)),('short_description_en',models.TextField(blank=True)),('image',models.ImageField(blank=True,upload_to='regions/covers/')),('cover_url',models.URLField(blank=True,help_text='Демо-сүрөт үчүн URL. Upload image болсо, ал артыкчылыктуу колдонулат.')),('is_featured',models.BooleanField(default=True))],options={'ordering':['name_ru'],'verbose_name':'Область','verbose_name_plural':'Области'}),
        migrations.CreateModel(name='Place', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('region',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='places',to='tours.region')),('slug',models.SlugField(unique=True)),('name_ky',models.CharField(max_length=160)),('name_ru',models.CharField(max_length=160)),('name_en',models.CharField(max_length=160)),('description_ky',models.TextField(blank=True)),('description_ru',models.TextField(blank=True)),('description_en',models.TextField(blank=True)),('image_url',models.URLField(blank=True,help_text='Демо-сүрөт URL')),('is_active',models.BooleanField(default=True)),('sort_order',models.PositiveIntegerField(default=0))],options={'ordering':['sort_order','name_ru'],'verbose_name':'Красивое место','verbose_name_plural':'Красивые места'}),
        migrations.CreateModel(name='Tour', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('region',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='tours',to='tours.region')),('category',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='tours',to='tours.category')),('slug',models.SlugField(unique=True)),('title_ky',models.CharField(max_length=180)),('title_ru',models.CharField(max_length=180)),('title_en',models.CharField(max_length=180)),('description_ky',models.TextField()),('description_ru',models.TextField()),('description_en',models.TextField()),('days',models.PositiveIntegerField(default=1)),('price_usd',models.DecimalField(decimal_places=2,max_digits=10)),('image',models.ImageField(blank=True,upload_to='tours/')),('is_featured',models.BooleanField(default=True)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True))],options={'ordering':['-is_featured','-created_at'],'verbose_name':'Тур','verbose_name_plural':'Туры'}),
        migrations.CreateModel(name='RegionImage', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('region',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='images',to='tours.region')),('image',models.ImageField(upload_to='regions/gallery/')),('caption_ky',models.CharField(blank=True,max_length=180)),('caption_ru',models.CharField(blank=True,max_length=180)),('caption_en',models.CharField(blank=True,max_length=180)),('sort_order',models.PositiveIntegerField(default=0))],options={'ordering':['sort_order','id'],'verbose_name':'Фото области','verbose_name_plural':'Фото области'}),
        migrations.CreateModel(name='PlaceImage', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('place',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='images',to='tours.place')),('image',models.ImageField(upload_to='places/')),('caption_ky',models.CharField(blank=True,max_length=180)),('caption_ru',models.CharField(blank=True,max_length=180)),('caption_en',models.CharField(blank=True,max_length=180)),('sort_order',models.PositiveIntegerField(default=0))],options={'ordering':['sort_order','id'],'verbose_name':'Фото места','verbose_name_plural':'Фото места'}),
        migrations.CreateModel(name='TourDay', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('tour',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='itinerary',to='tours.tour')),('day_number',models.PositiveIntegerField()),('title_ky',models.CharField(max_length=180)),('title_ru',models.CharField(max_length=180)),('title_en',models.CharField(max_length=180)),('description_ky',models.TextField(blank=True)),('description_ru',models.TextField(blank=True)),('description_en',models.TextField(blank=True))],options={'ordering':['day_number'],'unique_together':{('tour','day_number')},'verbose_name':'День тура','verbose_name_plural':'Дни тура'}),
        migrations.CreateModel(name='Booking', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('tour',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='bookings',to='tours.tour')),('name',models.CharField(max_length=120)),('email',models.EmailField(max_length=254)),('phone',models.CharField(blank=True,max_length=40)),('people',models.PositiveIntegerField(default=1)),('travel_date',models.DateField()),('message',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True))],options={'ordering':['-created_at']})
    ]
